#!/bin/bash

dir="`pwd`"

rad_home="`crad self --node-home`"

if [ $# -gt 0 ]
then
    exec bwrap --ro-bind /usr /usr --ro-bind /bin /bin --ro-bind /lib /lib --ro-bind /lib64 /lib64 --ro-bind /etc /etc --proc /proc --dev /dev --tmpfs /tmp --clearenv --unshare-all --share-net --bind "$rad_home" /tmp/.radicle --chdir /tmp --setenv HOME "/tmp" --setenv PATH "/tmp/.radicle/bin:/usr/bin:/bin" --setenv LANG "$LANG" --setenv TERM "$TERM" rad sync $@
else
    exec bwrap --ro-bind /usr /usr --ro-bind /bin /bin --ro-bind /lib /lib --ro-bind /lib64 /lib64 --ro-bind /etc /etc --proc /proc --dev /dev --tmpfs /tmp --clearenv --unshare-all --share-net --bind "$rad_home" /tmp/.radicle --bind $dir /tmp/workdir --chdir /tmp/workdir --setenv HOME "/tmp" --setenv PATH "/tmp/.radicle/bin:/usr/bin:/bin" --setenv LANG "$LANG" --setenv TERM "$TERM" rad sync
fi
